Spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-confiug-cxm-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-confiug-cxm-test
